dist: xenial
sudo: required

env:
  global:
   - PACKAGE_DIR=$HOME/packages
   - MINICONDA_DIR=$PACKAGE_DIR/miniconda
   - secure: "n2ndyY7KFHtiPCJXuRLv85ZkqOFAq0S5LAZN+nuv3asegIV+CIjl4/mfV9T3AI9WcFusdfFoTuar1B3C+33KMgICQi+vIPbRtkUQ4Al0TVrp4Soxs90Ls1E05PP7sp5tflmJtbRhd1A6PjYFH0UnLTR3t2e32SYBLS41zoAPOscIAG+aL3cYSC0HNZfj7/5kL+4dsbdzRk4cA2XKbmVt9CVUQrrreAmDDbBJYtY3DKliu07spU/kFIAhv8sIc3SJKswJAfh3aunDlxbmlI8Oh5Dtn1lyHSxVHoZ0jCPu1/2REwxq+QzYWU4w+fgv2alQUEPDphQkq2tvRzpkvF6DyGaAa+IsX+kUxmiAquASH7LASAX+ZnMqusa2T3lZFWBi5jLbbzoz9HN+fFqZZLCO4ef+CZejmWf2F6FAXAf9GIIjy8ZOXgzhHF9kzSMRHqYhU2QLV6f5Imsx4jheQGJd9t20WdEfOYXh3dsRrD2BKysF4pUMV+0p/1IAK2sjHzj6sySeUm8GGe2dsUoIDGRq0tOmYu1EL7vBLefFRUNWE3iBVTc6gi3SHYrtVBXGQ5cy7Pc+8HgyeRCpT92DLoDkENdC2paJQNS8sY6cB+QRdIotrdqicRVW5GpBjc0FTA8xYdb0k8UHzi13gvrae84sDpdYuDfnhRsdm13nsyZ8Gl4="
   - secure: "pW/9lzM/Yw5TWhKwEFSSRn+UbnR2yOPeodph1OtLSVUKizYHnZraMQlotJIzEaO7iXC63oS48fPr5f7sICLQ+8bwRuRCjvfegcT3weS1SqXtoqBBX4V9GQ1403tGI+vQEmJgYCArDsA2Jyv1o84fF8HpHNLOCzcvWhZ0haknOl849JnUhxs/+SyILA4UYT9uw1uHMpMSphV88WZBM9gd7xEwkzj++IAr9GI2tMMMBaD9y0sE3nUj2bJ2I3teGeXPkDbx+vDfL7M8/tdGz1b1Gn+OJ+umUsZrepHsvF2dQrgtHU44BoB+o8VoR0UNGzF+cbL914O0kdN9ewXi4/f2Vg3IsGoKZyXi6O38gq3eb0DiNHp4PDvk827Z6Bpr6ShwbHHhK7o5QhChBROUAV/jcAR8bLot3eEKmpdyoo7YuGu6h22lGvNog1B2WInNIn9B6+s4eEPtVWSCT4xlQ5l7BvEMdm2HpGzPi1YCrE945cta7wNj0DC/8ASHPNOSw32kAminHkcHMPt37qzRoJo44T/WpMlyQ9HinFEW3r3DdufgmLsyCHMV3/sej8ELQIND8oFK+1mnPrPpsmhoURuITocAMKMQHEfZrwaXabCQA21r13TnU7PJm31Mo5vfVFKgiv3Si4A5X9QXOORge7KCIOjWgAiNnkyr/c4t+bg8+nc="

jobs:
  include:

    - &deploy-conda-stage       # Conda for linux
      stage: deploy_tag
      name: "Deploy Conda"
      before_install:
        # Prepare folders
        - mkdir -p $MINICONDA_DIR
        # Bring all the tags
        #- git pull --unshallow
        - git pull
        # on OSX rogue needs an older version of the MacOS SDK
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            git clone https://github.com/phracker/MacOSX-SDKs;
            sudo mv MacOSX-SDKs/MacOSX10.9.sdk /opt/;
            export CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk;
            export CONDA_BUILD=1;
          fi

      install:
        # Install Anaconda for the right architecture (linux or osx)
        - cd $MINICONDA_DIR
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
          else
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda install conda-build anaconda-client
        - conda update -q conda conda-build

      before_script:
        # Go back to top directory
        - cd $TRAVIS_BUILD_DIR

      script:
        # Build conda package
        - conda build --debug recipes/pcas --output-folder bld-dir -c defaults -c lcls-ii -c conda-forge

      after_success:
        # Upload conda package
        - travis env list
        - anaconda -t $CONDA_UPLOAD_TOKEN_TAG upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2
        - anaconda -t $CONDA_UPLOAD_TOKEN_DEV upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2

    - <<: *deploy-conda-stage   # Conda for MacOS
      os: osx
      language: ruby  # osx does not support language=python

