{% set version = "4.13.2" %}

package:
  name: pcas
  version: {{ version }}

source:
  git_url: https://github.com/epics-modules/pcas.git
  git_tag: v{{ version }}

build:
  number: 6

requirements:
  build:
    - gcc_linux-64   [linux]
    - gxx_linux-64   [linux]
    - clang_osx-64   [osx]
    - clangxx_osx-64 [osx]
  host:
    - epics-base >=7
  run:
    - epics-base >=7
