{% set version = "7.0.2.2" %}

package:
  name: epics-base
  version: {{ version }}

source:
  git_url: https://github.com/epics-base/epics-base.git
  git_tag: R{{ version }}
  patches:
    - config_common.diff      # [linux]
    - config_common_osx.diff  # [osx]
    - pvdata_templates.diff   # [osx]

build:
  number: 0

requirements:
  build:
    - perl
    - readline
    - gcc_linux-64   [linux]
    - gxx_linux-64   [linux]
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]
  host:
    - readline
  run:
    - readline
