{% set version = "3.3.0" %}

package:
  name: p4p
  version: {{ version }}

source:
  git_url: https://github.com/mdavidsaver/p4p.git
  git_tag: {{ version }}

build:
  number: 4

requirements:
  build:
    - gcc_linux-64   [linux]
    - gxx_linux-64   [linux]
    - clang_osx-64   [osx]
    - clangxx_osx-64 [osx]
  host:
    - python
    - epics-base >=7
    - numpy
  run:
    - python
    - {{ pin_compatible('epics-base', max_pin='x.x.x.x') }}
    - numpy
  test:
    requires:
      - nose
    commands:
      - make nose
